# Generated by Django 5.0.7 on 2024-11-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_nfts_secreat_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfts',
            name='is_share',
            field=models.BooleanField(default=False),
        ),
    ]
